### ISSUE TITLE
No LaCrosse Events in OpenHAB 2

### ISSUE THREAD

**Issue by HAF-Blade** [csowada/openhab-bindings#10]
Hi,

I've tried to install the addon in OpenHAB 2. The Jeelink USB Receiver is shown in the things as online but I don't get any event receive messages in the log.

I've tried to follow the instructions here:
https://github.com/csowada/openhab-bindings/wiki/LaCrosse-Binding

The problem is that I'm fairly new to the topic and I've tried to add the line
lacrosse:port=/dev/ttyUSB0
to /etc/openhab2/openhab.cfg and to /etc/openhab2/services/openhab.cfg . 
Furthermore I've activated the "Legacy 1.x bindings" in the web gui.

Nothing happens. I also tried to add my LaCrosse temperature hardware manually but I don't have the needed IDs for the sensors.

I'm sure that I miss something. Is it possible to use the Jeelink binding at all in openhab2?

Oh by the way, I already used the hardware with FHEM where it worked.

Best regards,
Daniel

**Comment by csowada** [comment]
Sorry, but this binding is not compatible with OH2. I will not change this, but you are free to fork this repository. But I've seen a new binding on the OH community. I think that is the way to go.

https://community.openhab.org/t/new-jeelink-openhab2-binding/15018/13

**Comment by binbashblog** [comment]
No problem. Stopped using it a long time ago!

For info, ebusd on github, great solution.

Get Outlook for Android<https://aka.ms/ghei36>




On Thu, Jul 13, 2017 at 11:13 AM +0100, "csowada" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, but this binding is not compatible with OH2. I will not change this, but you are free to fork this repository. But I've seen a new binding on the OH community. I think that is the way to go.

https://community.openhab.org/t/new-jeelink-openhab2-binding/15018/13

-

**Comment by HAF-Blade** [comment]
Hi thanks for your answer. I appreciate this a lot. I will have a look at the linked addon. Thank you. :)

**Comment by binbashblog** [comment]
You may be interested in this! You’ll notice I have contributed in the forum:

https://forum.pimatic.org/topic/1160/how-to-control-vaillant-heating

It’s based off ebusd, great solution with a Raspberry Pi, this is what I use.

**Comment by csowada** [comment]
My answer was only releated to the LaCrosse binding, the ebus binding is still maintained. But I'm working on a native OH2 version since a couple of months. I hope I can release a first version in 2-3 months.
